CREATE TABLE ANSWER(
	SEQ NUMBER NOT NULL,
	ID VARCHAR2(10) NOT NULL,
	TITLE VARCHAR2(50) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	REFER NUMBER NOT NULL,
	STEP NUMBER NOT NULL,
	DEPTH NUMBER NOT NULL,
	READCOUNT NUMBER NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTRAINT ANSWER_PK PRIMARY KEY(SEQ)
);
 CREATE SEQUENCE ANSWER_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE MEMBERS(
ID VARCHAR2(10) NOT NULL,
PW VARCHAR2(25) NOT NULL,
NAME VARCHAR2(20) NOT NULL,
AUTH CHAR(1)NOT NULL,
DELFLAG CHAR(1) NOT NULL,
REGDATE DATE NOT NULL,
CONSTRAINT MEMBERS_CK CHECK(AUTH IN ('A','U')),
CONSTRAINT MEMBERS_PK PRIMARY KEY (ID)
);

ALTER TABLE ANSWER ADD CONSTRAINT ANSWER_FK FOREIGN KEY(ID) REFERENCES MEMBERS(ID);

INSERT INTO HAPPY.MEMBERS
(ID, PW, NAME, AUTH, DELFLAG, REGDATE)
VALUES('TEST002', 'TEST002', 'TEST', 'A', 'N', SYSDATE);

--Member
--boardselect
SELECT ID,PW,NAME,AUTH,DELFLAG,REGDATE FROM MEMBERS ORDER BY AUTH, REGDATE;

--signupmember
INSERT INTO HAPPY.MEMBERS
(ID, PW, NAME, AUTH, DELFLAG, REGDATE)
VALUES('TEST002', 'TEST002', 'TEST', 'U', 'N', SYSDATE);
--idduplicatecheck
SELECT COUNT(ID) ID FROM MEMBERS WHERE ID='TEST001';
--loginMember
SELECT ID,PW,AUTH,NAME FROM MEMBERS WHERE ID='TEST001'AND PW='TEST001';

-------------ANSWER
--writeBoard
INSERT INTO ANSWER
(SEQ, ID, TITLE, CONTENT, REFER, STEP, "DEPTH", READCOUNT, DELFALG, REGDATE)
VALUES(ANSWER_SEQ.NEXTVAL, 'TEST001', '클제목', '테스트',
(SELECT NVL(MAX(REFER),0)+1 FROM ANSWER), 0, 0, 0, 'N', SYSDATE);

--replyBoardUp
UPDATE ANSWER SET STEP =STEP+1
WHERE
STEP>(SELECT STEP FORM ANSWER WHERE SEQ='')
AND
REFER=(SELECT REFER FORM ANSWER WHERE SEQ='');

INSERT INTO ANSWER
(SEQ, ID, TITLE, CONTENT, REFER, STEP, "DEPTH", READCOUNT,DELFALG,REGDATE)
VALUES
(ANSWER_SEQ.NEXTVAL,'','','',
(SELECT REFER FROM ANSWER WHERE SEQ=''),(SELECT STEP+1 FROM ANSWER WHERE SEQ=''),
(SELECT DEPTH+1 FROM ANSWER WHERE SEQ=''),
0,'N',SYSDATE);

--getOneBoard
SELECT SEQ, ID, TITLE, CONTENT, REFER, STEP, "DEPTH", READCOUNT,DELFALG ,REGDATE
FROM ANSWER
WHERE SEQ='';

--readcountBoard
UPDATE ANSWER SET READCOUNT =READCOUNT+1 WHERE SEQ='';

--modifyBoard
UPDATE ANSWER SET TITLE='',CONTENT='' WHERE SEQ='';

--delflagBoard
UPDATE ANSWER SET DELFALG='Y' WHERE DELFALG='N' AND SEQ IN(,,);
--deleteBoardSel
SELECT SEQ, ID, TITLE, CONTENT, REFER, STEP, "DEPTH", READCOUNT, DELFALG , REGDATE
FROM ANSWER
WHERE REFER=(SELECT REFER FROM ANSWER WHERE SEQ='')
AND
	STEP>=(SELECT STEP FROM ANSWER WHERE SEQ='')
AND
	DEPTH>=(SELECT DEPTH FROM ANSWER WHERE SEQ='')
	ORDER BY REFER DESC,STEP;
--deleteBoard
DELETE FROM ANSWER WHERE SEQ IN(,);


SELECT SEQ, ID, TITLE, CONTENT, REFER, STEP, "DEPTH", READCOUNT, DELFALG , REGDATE
FROM ANSWER ORDER BY REFER DESC,STEP;
--userBoardList
SELECT SEQ, ID, TITLE, CONTENT, REFER, STEP, "DEPTH", READCOUNT, DELFALG , REGDATE
FROM(
SELECT ROWNUM RNUM,SEQ, ID, TITLE, CONTENT, REFER, STEP, "DEPTH", READCOUNT, DELFALG , REGDATE
FROM
(SELECT SEQ, ID, TITLE, CONTENT, REFER, STEP, "DEPTH", READCOUNT, DELFALG , REGDATE
FROM ANSWER
WHERE DELFALG='N'
ORDER BY REFER DESC,STEP)
)
WHERE RNUM BETWEEN 1 AND 10;

--userBoardListTotal
SELECT COUNT(*) FROM ANSWER WHERE DELFALG='N';

--adminBoardList
SELECT SEQ, ID, TITLE, CONTENT, REFER, STEP, "DEPTH", READCOUNT, DELFALG , REGDATE
FROM(
SELECT ROWNUM RNUM,SEQ, ID, TITLE, CONTENT, REFER, STEP, "DEPTH", READCOUNT, DELFALG , REGDATE
FROM
(SELECT SEQ, ID, TITLE, CONTENT, REFER, STEP, "DEPTH", READCOUNT, DELFALG , REGDATE
FROM ANSWER
ORDER BY REFER DESC,STEP)
)
WHERE RNUM BETWEEN 1 AND 10;

--adminBoardListTotal
SELECT COUNT(*) FROM ANSWER;
